scenarios:
  - name: insurance
    enabled: true
    keywords:
      # Страхование
      - "осаго"
      - "каско"
      - "страхов"
      - "зеленая карта"
      - "green card"
      - "полис"
      - "страховка"
      - "страховку"
      - "оформить"
      - "авто"
      - "онлайн"

      # Деньги / операции
      - "деньги"
      - "денеж"
      - "обмен"
      - "обменя"
      - "обменник"
      - "обменять"
      - "перев"
      - "перевод"
      - "перевести"
      - "переводить"

      # Валюты
      - "руб"
      - "rub"
      - "usd"
      - "доллар"
      - "долл"
      - "$"
      - "лари"
      - "gel"

      # Покупка / продажа
      - "куп"
      - "покуп"
      - "куплю"
      - "купить"
      - "покупка"
      - "покупаю"

      - "прод"
      - "прода"
      - "продам"
      - "продать"
      - "продажа"
      - "продаю"

      # Обмен наличных / курс
      - "нал"
      - "налич"
      - "кэш"
      - "cash"
      - "курс"
      - "валют"

      # Крипта / реквизиты
      - "usdt"
      - "крипт"
      - "карта"
      - "карты"
      - "счет"
      - "счёт"



#  - name: hotels
#    enabled: true
#    keywords:
#      - "гостиниц"
#      - "отель"
#      - "нужен номер"

#  - name: towing
#    enabled: true
#    keywords:
#      - "эвакуатор"
#      - "буксировк"
